### ISSUE TITLE
Colors invert randomly

### ISSUE THREAD

**Issue by Alerymin** [InfiniTimeOrg/InfiniTime#1984]
### Verification

- [x] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

Colors inverted for no apparent reason

### What should happen instead?

Colors should stay the same

### Reproduction steps

?

### More details?

Looks similar to #1022 but did not happen when charging
Happened on 2 different Infinitime watches
![IMG_20240119_193153_564](https://github.com/InfiniTimeOrg/InfiniTime/assets/55508107/0ba03cbd-202c-46df-a4a5-857cb7564047)
![IMG_20240119_193202_507](https://github.com/InfiniTimeOrg/InfiniTime/assets/55508107/549410da-5d11-4bb4-b229-7c5fa6ef6066)

### Version

1.14.0

**Comment by KaffeinatedKat** [comment]
yea i'm really not sure why this happens, and i've seen it occur multiple times while working with the display driver. My best guess is there is some issue with how we are writing to the LCD control register, and accidentally (perhaps an overflow) writing the command to invert the colors. I'll have to do some investigation to be sure though

**Comment by riban-bw** [comment]
I have seen this happen. Would a (temporary) work-around be to assert the flag to not invert colours when accessing a screen, e.g. watchface / info.

**Comment by DEPSUT** [comment]
This has happened to me, but I know a way of reproducing this issue.

You need to turn on lower wrist to put the watch to sleep and go to the paint app, then just keep holding the screen and lower it until the screen turns off, and after you turn the screen on again, all the colors are inverted, I have attached a video showing it.

It may have something to do with the issue #1992 

https://github.com/InfiniTimeOrg/InfiniTime/assets/77130196/e7b14534-f661-42e3-80b6-b7260d171014

**Comment by KaffeinatedKat** [comment]
I can reproduce this as well. This issue seems to also be the roots of the issue we're experiencing with #1869 (https://github.com/InfiniTimeOrg/InfiniTime/pull/1869#issuecomment-1915865847). There is some kind of issue with how the display is being controlled (SPI), which is causing unexpected behavior with the display

**Comment by mark9064** [comment]
Having a consistent repro is amazing, thanks!!!!

**Comment by Rathmox** [comment]
I managed to trigger this bug by turning off and on multiple times the watch. I never managed to reproduce it though.

**Comment by JF002** [comment]
I've just merged @2046! This issue will hopefully not occur again :) 
Thanks to @mark9064 for their great work!

**Comment by Saarsk** [comment]
> I've just merged @2046!

I think maybe you didn't intend to @ the user 2046 but instead refer to #2046? :)

**Comment by JF002** [comment]
> I think maybe you didn't intend to @ the user 2046 but instead refer to #2046? :)

You're right, thanks for letting me know about this typo (and sorry to user 2046 for the unexpected ping :) ).

**Comment by Ghoelian** [comment]
I just ran into this issue for the first time, running on the latest commit on main right now (commit 79ee886). Looks like it's not entirely fixed yet.

**Comment by Ghoelian** [comment]
Actually sorry nevermind, I didn't validate the firmware so it reverted back to some other commit I don't remember.

**Comment by Ghoelian** [comment]
Hey it's me again. The issue just resurfaced, this time on 1.15.0 (my own fork though).

Here's some pictures:

![Image](https://github.com/user-attachments/assets/fe757c7c-f748-45db-8276-b6662ff82f5a)

![Image](https://github.com/user-attachments/assets/76dbde92-fa0b-4358-8313-1266e260c797)

**Comment by KaffeinatedKat** [comment]
what does your fork modiy? This bug should no longer be possible with the fix that was merged

- John Crawford

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Ghoelian** [comment]
OTOH I added 2 settings related to vibration, and added a weather controller to a watchface. Could that have anything to do with this bug?

I'll look at the diff when I get home to be sure.

**Comment by 9cxndy** [comment]
I got hit by this as well. didn't happen when charging, lower wrist is turned on. I am running 728da0f4a08d327344aea with the background heartrate PR (#1718)

**Comment by Ghoelian** [comment]
@KaffeinatedKat it doesn't look to me like any changes I've made could be the cause, but I don't really understand this issue tbh.

Are there any logs I could extract somehow, should this happen again?

If you want you can see all the changes I'm running here:

https://github.com/InfiniTimeOrg/InfiniTime/compare/main...Ghoelian:InfiniTime:ghoelian

**Comment by grim42** [comment]
Can confirm it does occur on standard 1.15.0, not forked, had it happen randomly today
